### ISSUE TITLE
Skill duplicates in list 

### ISSUE THREAD

**Issue by FoKss-LTS** [supremetakoyaki/Aogami#3]
![Screenshot 2021-12-04 175455](https://user-images.githubusercontent.com/7655564/144717748-92d02132-0547-494f-974a-ec9a0de84ea2.png)

**Comment by supremetakoyaki** [comment]
These are duplicates present in the game, not because I accidentally added them twice.

**Comment by FoKss-LTS** [comment]
so what if i want to add Attack for example, which one should i add ?
